# Generated by Django 2.2.7 on 2019-11-28 05:11

import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('time', models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Time spent')),
                ('selected_difficulty', models.IntegerField(default=0, verbose_name='Difficulty')),
                ('position', models.IntegerField(default=0)),
                ('is_playing', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False, verbose_name='Fail status')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='Achieve status')),
                ('is_timeout', models.BooleanField(default=False, verbose_name='Timeout')),
                ('correct_answer', models.IntegerField(default=0, verbose_name='Number of correct answers')),
                ('wrong_answer', models.IntegerField(default=0, verbose_name='Number of wrong answers')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.DurationField(default=datetime.timedelta(0), verbose_name='Start point')),
                ('end_point', models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Stop point')),
                ('time_limit', models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Time limit')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizer_game.Player', verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=0, verbose_name='Number')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizer_game.Quiz', verbose_name='Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizer_game.Question'),
        ),
        migrations.AddField(
            model_name='player',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizer_game.Quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0, verbose_name='Value')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizer_game.Question', verbose_name='Question')),
            ],
        ),
    ]
