# Generated by Django 2.2.6 on 2019-11-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_vote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='downvotes',
            field=models.IntegerField(default=0, verbose_name='Downvote'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='upvotes',
            field=models.IntegerField(default=0, verbose_name='Upvote'),
        ),
    ]
