# Generated by Django 2.2.6 on 2019-11-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizer_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='text',
            new_name='topic',
        ),
    ]
