# Generated by Django 2.2.6 on 2019-11-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer_game', '0003_add_attributes_to_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
