# Generated by Django 2.2.6 on 2019-11-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizer_game', '0004_add_status_attributes_'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizer_game.Question'),
        ),
    ]
