# Generated by Django 2.2.6 on 2019-11-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizer_game', '0007_add_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='name',
        ),
    ]
