# Generated by Django 2.2.6 on 2019-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer_game', '0008_delete_timer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time',
            field=models.DurationField(blank=True, null=True, verbose_name='Time spent'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='end_point',
            field=models.DurationField(blank=True, null=True, verbose_name='Stop point'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_point',
            field=models.DurationField(blank=True, null=True, verbose_name='Start point'),
        ),
    ]
