# Generated by Django 2.2.6 on 2019-11-18 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer_game', '0009_change_timefield_to_durationfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='end_point',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Stop point'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_point',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Start point'),
        ),
    ]
