# Generated by Django 2.2.6 on 2019-11-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer_game', '0010_set_default_to_start_and_end_points_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='correct_answer',
            field=models.IntegerField(default=0, verbose_name='Number of correct answers'),
        ),
        migrations.AddField(
            model_name='player',
            name='wrong_answer',
            field=models.IntegerField(default=0, verbose_name='Number of wrong answers'),
        ),
    ]
