# Generated by Django 2.2.6 on 2019-11-22 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer_game', '0011_add_field_to_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_timeout',
            field=models.BooleanField(default=False, verbose_name='Timeout'),
        ),
        migrations.AddField(
            model_name='timer',
            name='time_limit',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Time limit'),
        ),
    ]
