# Generated by Django 2.2.6 on 2019-11-25 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer_game', '0012_add_time_limit_for_hard_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), verbose_name='Time spent'),
        ),
    ]
